'use strict';

// Seed content for the portal. Everything here is a starting draft: once the
// application is running, all revisions are managed through the admin console
// and stored in the database, not in this file.

const CHARTER = [
  '# Proposed Charter of the Professional Pool Players Union',
  '',
  'DRAFT FOR MEMBER REVIEW. Nothing in this document is binding until it is ratified',
  'under Article XI. Every clause is open for comment, and comments are anonymous.',
  '',
  '## Preamble',
  '',
  'We are the players. We fill the arenas, we draw the audiences, and we carry the risk.',
  'We travel at our own expense, we compete without guaranteed pay, and we accept',
  'conditions set entirely by promoters, sanctioning bodies, and broadcasters. We propose',
  'to organise so that the people who play the game have a formal, permanent, and',
  'accountable voice in how the game is run.',
  '',
  '## Article I. Name and Purpose',
  '',
  '1. The organisation shall be known as the Professional Pool Players Union, referred to',
  'in this charter as the Union.',
  '',
  '2. The purposes of the Union are:',
  '',
  '- To represent professional pool players in negotiations with tournament promoters,',
  'sanctioning bodies, broadcasters, venues, and sponsors.',
  '- To establish and enforce minimum standards for prize money, playing conditions,',
  'scheduling, and treatment of players.',
  '- To provide members with a grievance process that does not depend on the goodwill of',
  'the party being complained about.',
  '- To pool resources for health coverage, travel hardship, and legal support.',
  '- To collect and publish accurate data on player earnings, expenses, and event terms.',
  '',
  '## Article II. Jurisdiction and Eligibility',
  '',
  '1. Membership is open to any player who has competed in at least three sanctioned or',
  'promoter-run events for prize money in the preceding twenty-four months, in any',
  'recognised discipline including nine-ball, ten-ball, eight-ball, straight pool,',
  'one-pocket, bank pool, and rotation formats.',
  '',
  '2. Associate membership, without voting rights, is open to retired professionals,',
  'full-time instructors, and referees who support the purposes of the Union.',
  '',
  '3. No member may be excluded on the basis of nationality, sex, gender identity, race,',
  'religion, disability, age, or sexual orientation.',
  '',
  '4. The Union is international in scope. Regional chapters may be formed where at least',
  'twenty-five members reside in a common territory.',
  '',
  '## Article III. Rights of Members',
  '',
  '1. Every full member has one vote on ratification, amendments, officer elections, and',
  'any proposed collective agreement.',
  '',
  '2. Every member has the right to speak on Union business without retaliation, and to',
  'do so anonymously through the channels the Union provides.',
  '',
  '3. Every member has the right to inspect the financial records of the Union, the terms',
  'of any agreement negotiated on their behalf, and the minutes of Executive Board',
  'meetings.',
  '',
  '4. No member may be disciplined or expelled without written charges, notice, and a',
  'hearing before a panel that does not include the complaining party.',
  '',
  '## Article IV. Dues and Finances',
  '',
  '1. Annual dues shall be set on a sliding scale tied to declared competition earnings,',
  'with a floor for low-earning members and a cap for high earners. The founding',
  'proposal is a band from a nominal minimum to no more than one percent of prize',
  'earnings.',
  '',
  '2. Dues are waived for any member who declares hardship to the Membership Secretary.',
  'Hardship waivers are confidential and are not disclosed to the Executive Board by name.',
  '',
  '3. No officer may receive a salary from the Union in its first two years of operation.',
  'Reasonable expenses may be reimbursed against receipts.',
  '',
  '4. Accounts shall be independently reviewed each year and published to members in full.',
  '',
  '## Article V. Governance',
  '',
  '1. The governing body of the Union is the Members Assembly, consisting of all full',
  'members. The Assembly meets at least twice per year, and may meet electronically.',
  '',
  '2. Between meetings, the Union is administered by an Executive Board of seven members:',
  'a President, a Vice President, a Secretary, a Treasurer, and three at-large Directors.',
  '',
  '3. At least four of the seven Board seats must be held by players who are currently',
  'active in competition.',
  '',
  '4. The Board may not agree to any collective agreement, dues change, or amendment to',
  'this charter without a ratification vote of the membership.',
  '',
  '## Article VI. Elections',
  '',
  '1. Officers serve two-year terms, with a limit of three consecutive terms in any one',
  'office.',
  '',
  '2. Elections are conducted by secret ballot. Ballots are counted by an independent',
  'teller appointed by the Assembly and not standing for office.',
  '',
  '3. Any full member in good standing may stand for any office. Nomination requires the',
  'support of five other full members.',
  '',
  '4. A vacancy is filled by the runner-up in the most recent election for that seat, or,',
  'if none, by Board appointment until the next scheduled election.',
  '',
  '## Article VII. Collective Bargaining and Event Standards',
  '',
  '1. The Union shall seek recognition agreements with promoters and sanctioning bodies',
  'that give it the right to negotiate on behalf of participating players.',
  '',
  '2. The Union shall publish a schedule of Baseline Event Standards covering, at minimum:',
  '',
  '- Published prize distribution before entries open, with no post-event reduction.',
  '- Payment of prize money within thirty days of the conclusion of the event.',
  '- Written appearance and expense terms for invited players.',
  '- Table, lighting, cloth, and ball specifications, and a warm-up allocation.',
  '- Limits on consecutive scheduled matches and minimum rest between sessions.',
  '- Clear, published rules on dress code, shot clocks, and equipment.',
  '- Defined, non-arbitrary media and image rights, limited in scope and duration.',
  '- A named event official responsible for player welfare on site.',
  '',
  '3. No member is obliged to take part in any collective action, and no member may be',
  'disciplined for competing in an event the Union has not endorsed.',
  '',
  '## Article VIII. Grievances and Arbitration',
  '',
  '1. Any member may file a grievance concerning treatment by an event, a sponsor, an',
  'official, or the Union itself.',
  '',
  '2. Grievances are heard first by a Grievance Officer, then, if unresolved, by a panel',
  'of three members drawn at random from a standing pool, excluding anyone with a',
  'connection to the matter.',
  '',
  '3. The identity of a grievant is disclosed only to the extent strictly necessary to',
  'investigate, and never to the wider membership without written consent.',
  '',
  '## Article IX. Anti-Retaliation and Confidentiality',
  '',
  '1. Retaliation against a member for Union activity is itself a grievable offence and,',
  'where a recognition agreement is in force, a breach of that agreement.',
  '',
  '2. Deliberation records that identify individual members are kept confidential and are',
  'destroyed on a published schedule.',
  '',
  '3. Officers who disclose the identity of an anonymous commenter or a grievant may be',
  'removed from office by a simple majority of the Assembly.',
  '',
  '## Article X. Discipline',
  '',
  '1. A member may be suspended or expelled only for match-fixing, fraud against the',
  'Union or its members, violence or harassment against another member, or persistent',
  'non-payment of dues without a hardship waiver.',
  '',
  '2. Any disciplinary decision may be appealed to the Assembly.',
  '',
  '## Article XI. Ratification and Amendment',
  '',
  '1. This charter takes effect when it is approved by two-thirds of full members voting,',
  'with a quorum of one hundred full members or forty percent of the membership,',
  'whichever is lower.',
  '',
  '2. Amendments require thirty days notice, a published text, and approval by two-thirds',
  'of full members voting.',
  '',
  '3. All comments received on this portal before the ratification vote shall be compiled,',
  'in anonymous form, and circulated to the membership with the final text.',
  '',
  '## Article XII. Dissolution',
  '',
  '1. The Union may be dissolved by a three-quarters vote of full members.',
  '',
  '2. On dissolution, remaining assets shall be transferred to a hardship fund for',
  'professional players, and not distributed to officers or members individually.',
  '',
  '## How to comment on this draft',
  '',
  'Use the comment box at the foot of this page. Select the article your comment concerns',
  'so that it can be sorted during redrafting. Your name is never attached to your comment.',
  'You will appear under a stable pseudonym that is unique to you on this document.'
].join('\n');

const CASE_FOR_UNION = [
  '# The Case for Organising Now',
  '',
  'This paper sets out why the drafting committee believes a formal union, rather than an',
  'informal players association, is the right vehicle at this moment.',
  '',
  '## The structural problem',
  '',
  'Professional pool is one of the few elite competitive disciplines in which the athletes',
  'carry almost the entire commercial risk. Entry fees are paid up front. Travel,',
  'accommodation, and equipment come out of pocket. Prize money is concentrated at the top',
  'of the bracket, so the median competitor at a major event finishes the week out of',
  'pocket even when they play well.',
  '',
  'Meanwhile the terms of participation, the calendar, the format, the broadcast rights,',
  'and the disciplinary rules are all set by parties other than the players, and can be',
  'changed after players have already committed to travel.',
  '',
  '## Why informal representation has not worked',
  '',
  '- Ad hoc player committees dissolve when their founders stop competing.',
  '- Individual players who raise concerns are easy to isolate and are frequently punished',
  'with lost invitations rather than formal sanctions.',
  '- Without a standing legal identity, players cannot hold a contract, hold funds, or',
  'take collective action with any protection.',
  '- Verbal assurances from promoters are not enforceable and are not recorded.',
  '',
  '## What a union changes',
  '',
  '1. It creates a permanent counterparty that outlives any individual career.',
  '2. It converts private grievances into documented, aggregated evidence.',
  '3. It allows terms to be negotiated once, for everybody, instead of separately and',
  'unequally for each invited player.',
  '4. It gives players an anonymous route to speak, which is the only realistic route for',
  'anyone whose invitations depend on staying quiet.',
  '',
  '## What we are not proposing',
  '',
  'We are not proposing to run tournaments, to replace existing sanctioning bodies, or to',
  'stop anyone from competing where they choose. We are not proposing a strike. We are',
  'proposing a charter, a membership, and a seat at the table.',
  '',
  '## What we need from you',
  '',
  'Read the charter. Comment on the parts you think are wrong, weak, or missing. The',
  'drafting committee will publish a revised version with a change note for every round of',
  'comments, and every prior version stays readable on this site.'
].join('\n');

const EVENT_STANDARDS = [
  '# Baseline Event Standards: Opening Position',
  '',
  'This is the opening negotiating position referenced in Article VII of the charter. It',
  'is deliberately written as a floor, not a wish list.',
  '',
  '## 1. Money',
  '',
  '- The full prize distribution is published before entries open and cannot be reduced',
  'afterwards for any reason, including lower than expected entries.',
  '- Prize money is paid within thirty days of the final, by bank transfer, with a',
  'statement of any deductions.',
  '- Any withholding for taxes is itemised, with documentation sufficient for the player',
  'to claim relief in their home jurisdiction.',
  '- Entry fees are refundable in full if the event is cancelled or postponed by more than',
  'seven days.',
  '',
  '## 2. Conditions of play',
  '',
  '- Equipment specification for tables, cloth, balls, and lighting is published in advance',
  'and is the same for all rounds on the main arena.',
  '- Practice tables are available on site, in a published ratio to the field size.',
  '- A minimum rest period between matches, and a cap on matches per day per player.',
  '- No unannounced format change after the draw is published.',
  '',
  '## 3. Treatment of players',
  '',
  '- Written terms for any appearance fee, expense contribution, or media obligation.',
  '- Media and image rights limited to the promotion of that event and the archive of that',
  'event, for a defined period, and not sublicensed without consent.',
  '- A named welfare officer on site, and a published complaints route.',
  '- Accessible facilities and reasonable adjustment for disabled competitors.',
  '',
  '## 4. Discipline and fairness',
  '',
  '- Published rules, published shot clock policy, and published dress code, issued at',
  'least twenty-eight days before the event.',
  '- Any fine or sanction issued in writing with the rule cited and a right of appeal.',
  '- Referees briefed on a common interpretation, with a written decision log for',
  'contested calls.',
  '',
  '## 5. Data',
  '',
  '- The event provides anonymised participation and payout data to the Union annually so',
  'that the real economics of the tour can be published.',
  '',
  'Comment below if you think any of these is set at the wrong level, or if something',
  'that has cost you money is missing from the list.'
].join('\n');

const PRIVACY = [
  '# Member Privacy and Comment Anonymity',
  '',
  'This page explains exactly how this portal handles your information. It is written to',
  'be checked, not just trusted.',
  '',
  '## What we collect when you join',
  '',
  'Access is by invitation only. When you redeem an invitation you provide your name,',
  'email address, and optionally a phone number, your location, your competitive status,',
  'and any organisations you are affiliated with. This is used to verify that members are',
  'genuine professional players and to run votes and communications.',
  '',
  '## How your account is protected',
  '',
  '- Passwords are never stored. Only a salted scrypt hash is kept.',
  '- Two-factor authentication with an authenticator app is mandatory. You cannot finish',
  'registration without it.',
  '- One-time recovery codes are issued at registration and stored only as hashes.',
  '- Sessions are held in a server-side table and can be revoked by an administrator.',
  '',
  '## How comments stay anonymous',
  '',
  'Every comment you leave is shown under a pseudonym such as Chalk Fox 9A21. That',
  'pseudonym is derived from a keyed hash of your account and the specific document. It is',
  'stable, so other members can follow a conversation with you, but it is different on',
  'every document, so your remarks on one document cannot be linked to your remarks on',
  'another.',
  '',
  'The portal does not display your name, email, or handle next to a comment anywhere,',
  'including in the administrator console. Administrators can remove a comment, and can',
  'restore it, but the moderation screens show the same pseudonym that everyone else sees.',
  '',
  '## What administrators can and cannot see',
  '',
  'Administrators can see the membership roster, invitations, and the moderation queue.',
  'They can invite, suspend, and remove members, reset a member two-factor enrolment, and',
  'publish new versions of documents. Administrative actions are written to an audit log.',
  '',
  'Administrators cannot see who wrote a given comment through this application.',
  '',
  '## The honest limitation',
  '',
  'The comment record in the database does carry the author account id, because without it',
  'you could not withdraw your own comment and the site could not stop abuse. Anyone with',
  'direct access to the database server could therefore link a comment to an account. If',
  'the membership prefers, the drafting committee can move to storing only the derived',
  'pseudonym and dropping the author reference entirely. Say so in the comments.',
  '',
  '## Retention',
  '',
  'Comments and versions are retained until ratification is complete, then archived.',
  'Deleted comments are marked deleted and hidden rather than erased, so that moderation',
  'can be reviewed. Sessions expire automatically.'
].join('\n');

const ROADMAP = [
  '# Ratification Roadmap',
  '',
  'The drafting committee proposes the following sequence. Dates are indicative and will',
  'be confirmed once membership reaches the quorum threshold in Article XI.',
  '',
  '## Phase 1: Private circulation',
  '',
  'Invitations are issued to an initial cohort of active professionals. The charter is',
  'read and commented on. No public announcement is made. The aim is a working draft that',
  'the founding cohort will actually sign.',
  '',
  '## Phase 2: Redrafting',
  '',
  'The committee publishes a revised charter version approximately every three weeks, each',
  'with a change note explaining what moved and why. Previous versions stay available on',
  'this site so nobody has to take the summary on trust.',
  '',
  '## Phase 3: Widening',
  '',
  'Members invite other eligible players. The target is a founding membership large enough',
  'that no promoter can treat the Union as a handful of malcontents.',
  '',
  '## Phase 4: Ratification vote',
  '',
  'Thirty days notice, a frozen text, and a secret ballot. Two-thirds of votes cast, with',
  'the quorum set out in Article XI.',
  '',
  '## Phase 5: Incorporation and recognition',
  '',
  'Legal formation in a suitable jurisdiction, election of the first Executive Board, and',
  'the opening of recognition talks with promoters and sanctioning bodies.',
  '',
  '## How you can help right now',
  '',
  '- Comment on the charter, especially the parts you disagree with.',
  '- Tell the committee which events have treated you badly, in the comments, anonymously.',
  '- Ask an administrator for invitations for players you trust.'
].join('\n');

const FAQ = [
  '# Frequently Asked Questions',
  '',
  '## Will joining cost me invitations?',
  '',
  'That is the central risk, and it is why this portal is invitation-only and why comments',
  'are anonymous. The membership roster is not public. Nothing you write here carries your',
  'name.',
  '',
  '## Do I have to pay anything now?',
  '',
  'No. No dues are collected until after ratification, and Article IV proposes hardship',
  'waivers from the start.',
  '',
  '## Am I agreeing to anything by signing up?',
  '',
  'No. Creating an account gives you the right to read and comment. Ratification is a',
  'separate, explicit vote.',
  '',
  '## Why is two-factor authentication mandatory?',
  '',
  'Because a leaked membership list is the single most damaging thing that could happen to',
  'this effort. Passwords alone are not adequate protection for that list.',
  '',
  '## What happens if I lose my phone?',
  '',
  'Use one of the recovery codes issued when you registered. If those are gone as well,',
  'ask an administrator to reset your enrolment. You will be asked to set it up again on a',
  'new device.',
  '',
  '## Can I withdraw a comment?',
  '',
  'Yes. Your own comments show a withdraw option. Withdrawn and moderated comments are',
  'hidden from the discussion but the record is kept so that moderation can be audited.',
  '',
  '## Who runs this site?',
  '',
  'The drafting committee, until the first Executive Board is elected. After that, the',
  'Board appoints administrators and the audit log is open to any member on request.',
  '',
  '## Can I bring in another player?',
  '',
  'Ask an administrator to issue an invitation. Invitations are single use, can be tied to',
  'a specific email address, and expire.'
].join('\n');

const documents = [
  {
    slug: 'union-charter',
    title: 'Proposed Charter of the Professional Pool Players Union',
    summary: 'The central proposal. Read it, then comment article by article. Revised versions are published here with change notes.',
    kind: 'charter',
    isPrimary: true,
    sortOrder: 1,
    body: CHARTER
  },
  {
    slug: 'case-for-organising',
    title: 'The Case for Organising Now',
    summary: 'Why a formal union rather than another informal players association.',
    kind: 'document',
    isPrimary: false,
    sortOrder: 10,
    body: CASE_FOR_UNION
  },
  {
    slug: 'baseline-event-standards',
    title: 'Baseline Event Standards: Opening Position',
    summary: 'The minimum terms the Union would ask promoters and sanctioning bodies to meet.',
    kind: 'document',
    isPrimary: false,
    sortOrder: 20,
    body: EVENT_STANDARDS
  },
  {
    slug: 'privacy-and-anonymity',
    title: 'Member Privacy and Comment Anonymity',
    summary: 'Exactly what this portal stores, who can see it, and how comment anonymity works.',
    kind: 'document',
    isPrimary: false,
    sortOrder: 30,
    body: PRIVACY
  },
  {
    slug: 'ratification-roadmap',
    title: 'Ratification Roadmap',
    summary: 'The proposed sequence from private circulation to a ratification vote.',
    kind: 'document',
    isPrimary: false,
    sortOrder: 40,
    body: ROADMAP
  },
  {
    slug: 'member-faq',
    title: 'Frequently Asked Questions',
    summary: 'Short answers to the questions members ask before signing up.',
    kind: 'document',
    isPrimary: false,
    sortOrder: 50,
    body: FAQ
  }
];

module.exports = { documents };
